# Generated by Django 4.2.14 on 2024-08-03 21:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pollster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_pollster', models.CharField(max_length=75)),
                ('info', models.TextField()),
                ('quality_of_pollster', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harris_support', models.FloatField()),
                ('trump_support', models.FloatField()),
                ('third_party_support', models.FloatField(null=True)),
                ('date_published', models.DateField()),
                ('link_to_poll', models.URLField(null=True)),
                ('type_of_voters', models.CharField(max_length=50)),
                ('number_of_respondents', models.IntegerField()),
                ('pollster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='main.pollster')),
            ],
        ),
    ]
