# Generated by Django 4.2.14 on 2024-08-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_poll_third_party_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='region',
            field=models.CharField(default='national', max_length=50),
            preserve_default=False,
        ),
    ]
