# Generated by Django 4.2.14 on 2024-08-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_poll_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='margin',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
