# Generated by Django 4.2.14 on 2024-08-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_poll_margin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='margin',
            field=models.IntegerField(),
        ),
    ]
