# Generated by Django 4.2.14 on 2024-08-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_poll_margin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll_Aggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('trump_support', models.FloatField()),
                ('harris_support', models.FloatField()),
                ('kennedy_support', models.FloatField(blank=True, null=True)),
                ('includes_third_party', models.BooleanField(default=False)),
            ],
        ),
    ]
