# Generated by Django 4.2.14 on 2024-08-17 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_poll_aggregate_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='poll_aggregate',
            unique_together={('date', 'includes_third_party')},
        ),
    ]
