# Generated by Django 4.2.14 on 2024-08-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_poll_aggregate_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='poll_aggregate',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='poll_aggregate',
            constraint=models.UniqueConstraint(fields=('date', 'includes_third_party'), name='unique_date_includes_third_party'),
        ),
    ]
